#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 12 15:19:07 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.1.zip
